backend:
  name: git-gateway
  branch: master

# Enable local backend for working with local repo
# https://www.netlifycms.org/docs/beta-features/
# npx netlify-cms-proxy-server
local_backend: true

# Enable drafts
# publish_mode: editorial_workflow

media_folder: "src/img"
public_folder: "/img"
collections:
  
  - label: "Pages"
    name: "pages"
    files:
      - label: "Home"
        name: "index"
        file: "src/_data/index.json"
        fields:
          - {label: Image, name: index_image, widget: image}
          - {label: Image Alt, name: index_image_alt, widget: string}
      - label: "About"
        name: "about"
        file: "src/_data/about.json"
        fields:
          - {label: Text, name: about_text, widget: markdown}
          - {label: Image, name: about_image, widget: image}
          - {label: Image Alt, name: about_image_alt, widget: string}
      - label: "Contact"
        name: "contact"
        file: "src/_data/contact.json"
        fields:
          - {label: Text, name: text, widget: markdown}
  - label: "Stories"
    name: "stories"
    folder: "src/stories"
    create: true
    # slug: "{{ slug }}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Author", name: "author", widget: "string", default: "Royee Zvi Atadgy" }
      - { label: "Preview", name: "description", widget: "markdown" }
      # - { label: "Tags", name: "tags", widget: "list", default: ["post"] }
      - { label: "Body", name: "body", widget: "markdown" }
  - label: "Published"
    name: "published"
    folder: "src/published"
    create: true
    # slug: "{{ slug }}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publication", name: "publication", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Author", name: "author", widget: "string", default: "Royee Zvi Atadgy" }
      # - { label: "Tags", name: "tags", widget: "list", default: ["post"] }
      - { label: "Body", name: "body", widget: "markdown" }
  - label: "Essays"
    name: "essays"
    folder: "src/essays"
    create: true
    # slug: "{{ slug }}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publication", name: "publication", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Author", name: "author", widget: "string", default: "Royee Zvi Atadgy" }
      # - { label: "Tags", name: "tags", widget: "list", default: ["post"] }
      - { label: "Body", name: "body", widget: "markdown" }
  - label: "Site Configuration"
    name: "site"
    files:
      - label: "Footer"
        name: "footer"
        file: "src/_data/site.json"
        fields:
          - {label: Copyright, name: copyright, widget: string}